### ISSUE TITLE
Get after an isA crashes

### ISSUE THREAD

**Issue by dave08** [robfletcher/strikt#132]
```kotlin
data class Test(val a: String)
data class Test2(val b: String)

val i = Test("this")

expectThat(i) {
	isA<Test2>().get { b }.isEqualTo("that")
}
```

Throws

```
	at strikt.internal.AssertionBuilder.get(AssertionBuilder.kt:64)
	at strikt.api.Assertion$Builder$DefaultImpls.get(Assertion.kt:233)
	at strikt.api.DescribeableBuilder$DefaultImpls.get(DescribeableBuilder.kt)
	at strikt.internal.AssertionBuilder.get(AssertionBuilder.kt:10)
```

Instead of giving a report of the error.

**Comment by robfletcher** [comment]
This is a bug. It shouldn't even be evaluating the `get` if the `isA` fails.
