### ISSUE TITLE
Suppress strikt stack frames in thrown assertion errors

### ISSUE THREAD

**Issue by DanielThomas** [robfletcher/strikt#136]
Currently when strikt throws an assertion error there's a bunch of internal implementation noise, pushing the code under test down the stack trace quite a way:

```
org.opentest4j.AssertionFailedError: ▼ Expect that {"4762073"=false}:
  ✗ is empty
	at strikt.internal.AssertionStrategy.createAssertionFailedError$strikt_core(AssertionStrategy.kt:180)
	at strikt.internal.AssertionStrategy$Throwing.afterStatusSet(AssertionStrategy.kt:129)
	at strikt.internal.AssertionStrategy$appendAtomic$1.fail(AssertionStrategy.kt:35)
	at strikt.api.Assertion$DefaultImpls.fail$default(Assertion.kt:26)
	at strikt.api.Assertion$Builder$assertThat$$inlined$apply$lambda$1.invoke(Assertion.kt:152)
	at strikt.api.Assertion$Builder$assertThat$$inlined$apply$lambda$1.invoke(Assertion.kt:35)
	at strikt.internal.AssertionBuilder.assert(AssertionBuilder.kt:38)
	at strikt.internal.AssertionBuilder.assert(AssertionBuilder.kt:10)
	at strikt.api.Assertion$Builder$DefaultImpls.assert(Assertion.kt:56)
	at strikt.api.DescribeableBuilder$DefaultImpls.assert(DescribeableBuilder.kt)
	at strikt.internal.AssertionBuilder.assert(AssertionBuilder.kt:10)
	at strikt.api.Assertion$Builder$DefaultImpls.assertThat(Assertion.kt:151)
	at strikt.api.DescribeableBuilder$DefaultImpls.assertThat(DescribeableBuilder.kt)
	at strikt.internal.AssertionBuilder.assertThat(AssertionBuilder.kt:10)
	at strikt.assertions.MapKt.isEmpty(Map.kt:10)
	at com.netflix.astrid.core.module.RedisModuleProducerTest.there are no orphaned keys(RedisModuleProducerTest.kt:129)
```

When constructing the `AssertionFailedError` in `AssertionStrategy#createAssertionFailedError` blindly, I'd filter the `strikt.*` stack frames and put them into an suppressed exception. That'll mean the top of the stack trace is always the location where the assertion is, but allows troubleshooting/tracing of strikt internals if required.

**Comment by robfletcher** [comment]
I like it.

**Comment by robfletcher** [comment]
Where’s that PR @DanielThomas? 😋

**Comment by mkobit** [comment]
Didn't realize how much I missed this from other assertions frameworks. Really looking forward to whenever this gets done (might take a crack at it if I have a chance soon).
