### ISSUE TITLE
Assertion failed are not shown without adding opentest4j dependency.

### ISSUE THREAD

**Issue by lenguyenthanh** [robfletcher/strikt#180]
Before adding `opentest4j` dependency, it shows this exception whenever assertion failed occur:
```org/opentest4j/AssertionFailedError
java.lang.NoClassDefFoundError: org/opentest4j/AssertionFailedError
	at strikt.internal.AssertionStrategy.createAssertionFailedError$strikt_core(AssertionStrategy.kt:195)
	at strikt.internal.AssertionStrategy$Throwing.afterStatusSet(AssertionStrategy.kt:151)
	at strikt.internal.AssertionStrategy$appendAtomic$1.fail(AssertionStrategy.kt:44)
	at strikt.api.AtomicAssertion$DefaultImpls.fail$default(AtomicAssertion.kt:19)
	at strikt.assertions.CollectionKt$hasSize$1.invoke(Collection.kt:12)
	at strikt.assertions.CollectionKt$hasSize$1.invoke(Collection.kt)
	at strikt.internal.AssertionBuilder.assert(AssertionBuilder.kt:64)
	at strikt.internal.AssertionBuilder.assert(AssertionBuilder.kt:11)
	at strikt.assertions.CollectionKt.hasSize(Collection.kt:9)
       at ....
	at org.spekframework.spek2.runtime.scope.TestScopeImpl.execute(Scopes.kt:94)
	at org.spekframework.spek2.runtime.Executor$execute$$inlined$executeSafely$lambda$1$1.invokeSuspend(Executor.kt:52)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
Caused by: java.lang.ClassNotFoundException: org.opentest4j.AssertionFailedError
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more
```

After I added `testImplementation group: 'org.opentest4j', name: 'opentest4j', version: '1.2.0'`, everything works fine.

I'm using [spek](https://github.com/spekframework/spek) version `2.0.6` for testing an Android app. It works fine with other assertion library like AssertJ.

P/S I think it is still not fine after I adding `opentest4j` dependency. Here is what I got after addin the dependency:

```▼ Expect that [Mock for Class, hashCode: 17337594]:
  ✗ has size 2 : found 1
org.opentest4j.AssertionFailedError: ▼ Expect that [Mock for Class, hashCode: 17337594]:
  ✗ has size 2 : found 1
	at ...
	at ....
	at org.spekframework.spek2.runtime.scope.TestScopeImpl.execute(Scopes.kt:94)
	at org.spekframework.spek2.runtime.Executor$execute$$inlined$executeSafely$lambda$1$1.invokeSuspend(Executor.kt:52)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	Suppressed: org.opentest4j.AssertionFailedError
		at strikt.internal.AssertionStrategy.createAssertionFailedError$strikt_core(AssertionStrategy.kt:195)
		at strikt.internal.AssertionStrategy$Throwing.afterStatusSet(AssertionStrategy.kt:151)
		at strikt.internal.AssertionStrategy$appendAtomic$1.fail(AssertionStrategy.kt:44)
		at strikt.api.AtomicAssertion$DefaultImpls.fail$default(AtomicAssertion.kt:19)
		at strikt.assertions.CollectionKt$hasSize$1.invoke(Collection.kt:12)
		at strikt.assertions.CollectionKt$hasSize$1.invoke(Collection.kt)
		at strikt.internal.AssertionBuilder.assert(AssertionBuilder.kt:64)
		at strikt.internal.AssertionBuilder.assert(AssertionBuilder.kt:11)
```

**Comment by robfletcher** [comment]
Weird, that should be pulled in transitively. What does your dependency on Strikt look like?

**Comment by lenguyenthanh** [comment]
Here are all my test dependencies:
```    // Spek
    testImplementation "org.spekframework.spek2:spek-dsl-jvm:$spek_version"
    testImplementation "org.spekframework.spek2:spek-runner-junit5:$spek_version"
    // Spek requires kotlin-reflect, omit when already in classpath
    testImplementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    testImplementation 'org.mockito:mockito-core:2.28.2'
    testImplementation "com.nhaarman.mockitokotlin2:mockito-kotlin:2.1.0"
    testImplementation "org.assertj:assertj-core:3.13.2"
    testImplementation("io.strikt:strikt-core:0.22.1")
    testImplementation group: 'org.opentest4j', name: 'opentest4j', version: '1.2.0'
```

**Comment by lenguyenthanh** [comment]
Assertion failed messages still don't look nice with new version `0.22.2`
It looks like this now:
```  ✗ has size 2 : found 1
org.opentest4j.AssertionFailedError: ▼ Expect that [Mock for Class, hashCode: 17337594]:
  ✗ has size 2 : found 1
	at ...
	at ....
	at org.spekframework.spek2.runtime.scope.TestScopeImpl.execute(Scopes.kt:94)
	at org.spekframework.spek2.runtime.Executor$execute$$inlined$executeSafely$lambda$1$1.invokeSuspend(Executor.kt:52)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	Suppressed: org.opentest4j.AssertionFailedError
		at strikt.internal.AssertionStrategy.createAssertionFailedError$strikt_core(AssertionStrategy.kt:195)
		at strikt.internal.AssertionStrategy$Throwing.afterStatusSet(AssertionStrategy.kt:151)
		at strikt.internal.AssertionStrategy$appendAtomic$1.fail(AssertionStrategy.kt:44)
		at strikt.api.AtomicAssertion$DefaultImpls.fail$default(AtomicAssertion.kt:19)
		at strikt.assertions.CollectionKt$hasSize$1.invoke(Collection.kt:12)
		at strikt.assertions.CollectionKt$hasSize$1.invoke(Collection.kt)
		at strikt.internal.AssertionBuilder.assert(AssertionBuilder.kt:64)
		at strikt.internal.AssertionBuilder.assert(AssertionBuilder.kt:11)```

Maybe other issue?

**Comment by robfletcher** [comment]
What’s the problem specifically there?

**Comment by lenguyenthanh** [comment]
I expect it has no `Suppressed: org.opentest4j.AssertionFailedError` at the end. But it's not really important.

**Comment by robfletcher** [comment]
That’s a deliberate bit of behavior so that the stack trace originates at the line in your test where the assertion is. Any internal stack frames from the strikt code are shifted into the suppressed section.

**Comment by lenguyenthanh** [comment]
Got it, thanks for quick fix and update!

**Comment by robfletcher** [comment]
No problem. Thanks for the bug report!
