### ISSUE TITLE
Test failures after switch from 0.26.1 to 0.27.0 with Kotlin 1.3.72

### ISSUE THREAD

**Issue by tmohme** [robfletcher/strikt#227]
After switching from 0.26.1 to 0.27.0 (leaving everything else untouched) I get two test failures:

```
java.lang.NoSuchMethodError: 'void kotlin.jvm.internal.FunctionReferenceImpl.<init>(int, java.lang.Class, java.lang.String, java.lang.String, int)'

	at strikt.assertions.CollectionKt$isEmpty$1.<init>(Collection.kt)
	at strikt.assertions.CollectionKt$isEmpty$1.<clinit>(Collection.kt)
	at strikt.assertions.CollectionKt.isEmpty(Collection.kt:20)
	at org.acme.authorization.adapter.configuration.ConfigurationParserTest.parses a single Chapter without Properties(ConfigurationParserTest.kt:33)
```
 with source line#33 being `expectThat(aChapter.propertyKeys).isEmpty()` where "aChapter.propertyKeys" is a `Set<PropertyKey>`

and 

```
java.lang.NoClassDefFoundError: Could not initialize class strikt.assertions.CollectionKt$isEmpty$1

	at strikt.assertions.CollectionKt.isEmpty(Collection.kt:20)
	at org.acme.authorization.adapter.configuration.ConfigurationParserTest.parses an empty Configuration(ConfigurationParserTest.kt:20)
```
 with source line#20 being `expectThat(configuration.chapterNames).isEmpty()` where "configuration.chapterNames" is a `Set<ChapterName>`.

Unfortunately I wasn't able to step into strikt's source code to investigate it further.
I'm still running Kotlin 1.3.72 on top of various Java11 VMs (OpenJDK, Zulu).

Did I miss required adaption for the switch?

**Comment by cjbrooks12** [comment]
0.27.0 adds compatibility with Kotlin 1.4. I do not think libraries compiled with 1.4 can be used in 1.3.*.

**Comment by tmohme** [comment]
Hm . . . I'm not sure if this is the case.
At least "[Migrating to Kotlin 1.4](https://kotlinlang.org/docs/reference/whatsnew14.html#migrating-to-kotlin-140)" doesn't mention a general backward incompatibility.

Unfortunately it is pretty difficult for me to run my project with Kotlin 1.4 to cross-check the issue.
