### ISSUE TITLE
failing containsExactly expectation logs error twice.

### ISSUE THREAD

**Issue by christophsturm** [robfletcher/strikt#59]
or maybe even three times if you count the expected: null

this is with current master.

the output for this one line:
`        expect(listOf(1,2,3)).containsExactly(1,2)`

is 
```
Expected :null
Actual   :[3]
 <Click to see difference>



strikt.internal.opentest4j.CompoundAssertionFailure: ✗ contains exactly the elements [1, 2]
  ✗ contains no further elements : found [3]

	at strikt.internal.CompoundAssertionNode.toError(AssertionNode.kt:136)
	at strikt.internal.AssertionNodeKt.toErrors(AssertionNode.kt:144)
	at strikt.internal.AssertionNodeKt.access$toErrors(AssertionNode.kt:1)
	at strikt.internal.AssertionSubject.toError(AssertionNode.kt:73)
	at strikt.internal.AssertionGroup$DefaultImpls.throwOnFailure(AssertionNode.kt:31)
	at strikt.internal.AssertionSubject.throwOnFailure(AssertionNode.kt:40)
	at strikt.internal.AsserterImpl.throwOnFailure(AsserterImpl.kt:168)
	at strikt.internal.AsserterImpl.access$throwOnFailure(AsserterImpl.kt:15)
	at strikt.internal.AsserterImpl$compose$$inlined$let$lambda$1.then(AsserterImpl.kt:147)
	at strikt.assertions.IterableKt.containsExactly(Iterable.kt:145)
...

strikt.internal.opentest4j.CompoundAssertionFailure: ▼ Expect that [1, 2, 3]:
  ✗ contains exactly the elements [1, 2]
    ✗ contains no further elements : found [3]

	at strikt.internal.AssertionSubject.toError(AssertionNode.kt:73)
	at strikt.internal.AssertionGroup$DefaultImpls.throwOnFailure(AssertionNode.kt:31)
	at strikt.internal.AssertionSubject.throwOnFailure(AssertionNode.kt:40)
	at strikt.internal.AsserterImpl.throwOnFailure(AsserterImpl.kt:168)
	at strikt.internal.AsserterImpl.access$throwOnFailure(AsserterImpl.kt:15)
	at strikt.internal.AsserterImpl$compose$$inlined$let$lambda$1.then(AsserterImpl.kt:147)
	at strikt.assertions.IterableKt.containsExactly(Iterable.kt:145)
...
```

at least in idea.

**Comment by christophsturm** [comment]
the real error message is now fixed, but there is still the expected: actual: part and that one is now wrong in a different way than before:
```
Expected :[1, 2]
Actual   :null
 <Click to see difference>
```

**Comment by robfletcher** [comment]
Closing this because the remaining issue is captured by #74

**Comment by christophsturm** [comment]
with 0.11.5 this is again logged twice
```
strikt.internal.opentest4j.AtomicAssertionFailure: ▼ Expect that [1, 2, 3]:
  ✗ contains exactly the elements [1, 2]

	at strikt.internal.AssertionResult$DefaultImpls.toError(AssertionNode.kt:40)
	at strikt.internal.CompoundAssertionNode.toError(AssertionNode.kt:104)
	at strikt.internal.AssertionSubject.toError(AssertionNode.kt:78)
	at strikt.internal.AssertionBuilder.throwOnFailure(AssertionBuilder.kt:150)
	at strikt.internal.AssertionBuilder.access$throwOnFailure(AssertionBuilder.kt:18)
	at strikt.internal.AssertionBuilder$compose$$inlined$let$lambda$1.then(AssertionBuilder.kt:125)
	at strikt.assertions.IterableKt.containsExactly(Iterable.kt:175)
	at strikt.assertions.IterableKt.containsExactly(Iterable.kt:138)
	at de.rexch.market.it.TradeIT.users can close counter bids on their own postings(TradeIT.kt:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:515)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:131)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:107)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:169)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:113)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:107)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:169)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:113)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:107)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:169)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1603)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)


strikt.internal.opentest4j.CompoundAssertionFailure: ▼ Expect that [1, 2, 3]:
  ✗ contains exactly the elements [1, 2]
    ✓ contains 1
    ✓ …at index 0
    ✓ contains 2
    ✓ …at index 1
    ✗ contains no further elements : found [3]

	at strikt.internal.AssertionSubject.toError(AssertionNode.kt:82)
	at strikt.internal.AssertionBuilder.throwOnFailure(AssertionBuilder.kt:150)
	at strikt.internal.AssertionBuilder.access$throwOnFailure(AssertionBuilder.kt:18)
	at strikt.internal.AssertionBuilder$compose$$inlined$let$lambda$1.then(AssertionBuilder.kt:125)
	at strikt.assertions.IterableKt.containsExactly(Iterable.kt:175)
	at strikt.assertions.IterableKt.containsExactly(Iterable.kt:138)
	at de.rexch.market.it.TradeIT.users can close counter bids on their own postings(TradeIT.kt:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:515)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:131)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:107)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:169)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:113)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:107)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:169)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:113)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:107)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:169)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1603)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by robfletcher** [comment]
Logging two exceptions is expected. The compound exception contains the atomic ones (only one in this case). If further sub-assertions had failed you'd see more. The issue I see with what's being logged is that the atomic exception is missing a level of information.

**Comment by christophsturm** [comment]
ok but its just one assertion. if its internally split up into more that's an implementation detail. I mean it's not a big deal but still surprising.

**Comment by cjbrooks12** [comment]
A better pattern here might be _only_ show the atomic message if the compound one only has a single child failure. And if there are multiple, then include messaging to say something like "Compound failure included the following other failures"

**Comment by robfletcher** [comment]
Yeah, if it's confusing it may be worth moving away from the opentest4j exception types that provide this behavior. I don't want to break the way IntelliJ presents a diff dialog, though.
